bcgov/MOH-AOP-OOP

- oop/src/App.vue
- oop/src/components/Button.vue
- oop/src/components/ContinueBar.vue
- oop/src/components/Loader.vue
- oop/src/components/ProgressBar.vue
- oop/src/router/index.js
- oop/src/router/routes.js
- oop/src/router/step-routes.js
- oop/src/views/AccountTypePage.vue
- oop/src/views/DependentPage.vue
- oop/src/views/HomePage.vue
- oop/src/views/MoveInfoPage.vue
- oop/src/views/ReviewPage.vue
- oop/src/views/SubmissionErrorPage.vue
- oop/src/views/SubmissionPage.vue
- oop/src/views/YourInfoPage.vue
> Add progress bar to OOP.

- oop/package-lock.json
- oop/package.json
- oop/src/App.vue
- oop/src/locale/strings.en.js
- oop/src/router/index.js
- oop/src/router/routes.js
- oop/src/services/page-state-service.js
- oop/src/views/AccountTypePage.vue
- oop/src/views/MoveInfoPage.vue
- oop/src/views/YourInfoPage.vue
> Add page navigation "back" button press blockers.

- oop/src/views/HomePage.vue
> OOP: Home page fixes.

- oop/package-lock.json
- oop/package.json
- oop/src/components/DateInput.vue
- oop/src/router/routes.js
- oop/src/views/MoveInfoPage.vue
- oop/vue.config.js
> OOP: Fixed `publicPath` vue config.

- oop/package-lock.json
- oop/package.json
- oop/src/components/PhnInput.vue
- oop/src/components/PostalCodeInput.vue
- oop/src/views/YourInfoPage.vue
> OOP: `Last Name` and `PHN` client-side validation.

- oop/src/components/PhnInput.vue
- oop/src/components/PostalCodeInput.vue
- oop/src/views/YourInfoPage.vue
> OOP: Fixed `Last Name` and `PHN` validations.

- oop/package-lock.json
- oop/package.json
- oop/src/App.vue
- oop/src/components/Input.vue
- oop/src/helpers/scroll.js
- oop/src/views/YourInfoPage.vue
> Added new common-lib-vue package and added "Your Info" page validation.

- oop/package-lock.json
- oop/package.json
- oop/src/views/MoveInfoPage.vue
> Added validation for Permanent Move and Arrival dates

- oop/src/store/modules/form.js
- oop/src/views/AccountTypePage.vue
- oop/tests/unit/views/YourInfoPage.spec.js
> Added validations to AccountTypePage.

- oop/src/components/ProgressBar.vue
- oop/src/router/index.js
- oop/src/services/page-state-service.js
- oop/src/views/AccountTypePage.vue
- oop/src/views/HomePage.vue
- oop/src/views/YourInfoPage.vue
> Allow back navigation via stepper.

- oop/package-lock.json
- oop/package.json
> OOP version bump (v0.1.9).

- oop/package-lock.json
- oop/package.json
- oop/src/helpers/scroll.js
- oop/src/store/states/form-dummy-data.js
- oop/src/views/AccountTypePage.vue
> OOPDEF-45: Account Type page validations.

- oop/src/components/DateInput.vue
- oop/src/views/MoveInfoPage.vue
> Fixed "No error should be displayed as a person can depart and arrive on the same date"

- oop/package-lock.json
- oop/package.json
- oop/src/views/YourInfoPage.vue
> OOPDEF-95: Update to common-lib-vue version, and update to error messages.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump.

- oop/package-lock.json
- oop/package.json
- oop/src/App.vue
- oop/src/components/ContinueBar.vue
- oop/src/components/PageContent.vue
- oop/src/components/ProgressBar.vue
- oop/src/helpers/scroll.js
- oop/src/views/AccountTypePage.vue
- oop/src/views/HomePage.vue
- oop/src/views/YourInfoPage.vue
> OOPDEF-97: Fixed footer white space.

- oop/package-lock.json
- oop/package.json
- oop/src/components/DateInput.vue
- oop/src/views/MoveInfoPage.vue
> OOPDEF-108 and 109 (Day and Year fields bugs)

- oop/package-lock.json
- oop/package.json
- oop/src/store/modules/form.js
- oop/src/views/AccountTypePage.vue
> OOP: AccountTypePage dependent PHN validations.

- oop/package-lock.json
- oop/package.json
- oop/src/components/ProgressBar.vue
> OOPDEF-98: Updated Header, Footer and stepper width/height.

- oop/src/views/AccountTypePage.vue
- oop/src/views/HomePage.vue
- oop/src/views/MoveInfoPage.vue
- oop/src/views/YourInfoPage.vue
> OOPDEF-113: Updated text on pages.

- oop/package-lock.json
- oop/src/views/MoveInfoPage.vue
> OOPDEF 117 - Address line, City, Province and Postal are mandatory fields

- oop/src/main.js
> OOPDEF-122: Add polyfill for IE validation bug.

- oop/src/views/MoveInfoPage.vue
> Fixed optional fields for Address

- oop/package-lock.json
- oop/package.json
- oop/src/components/ReviewTable.vue
- oop/src/components/ReviewTableList.vue
- oop/src/helpers/date.js
- oop/src/main.js
- oop/src/store/states/form-dummy-data.js
- oop/src/views/ReviewPage.vue
> OOPDEF-61: Added "Review" page.

- oop/src/components/ProvinceInput.vue
- oop/src/helpers/validators.js
- oop/src/views/MoveInfoPage.vue
> OOPDEF-120 - Added non-BC validation for Province

- oop/src/views/MoveInfoPage.vue
> OOPDEF-115 - User is getting error when entered address outside BC (within Canada)

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.14).

- oop/package-lock.json
- oop/package.json
- oop/src/components/ReviewTableList.vue
- oop/src/main.js
- oop/src/store/states/form-dummy-data.js
- oop/src/views/ReviewPage.vue
- oop/src/views/SubmissionPage.vue
> OOPDEF-65: Submission page.

- oop/package-lock.json
- oop/src/views/MoveInfoPage.vue
> Changes in removing previous values when country is changed and modified error messages

- oop/package-lock.json
- oop/src/components/DateInput.vue
- oop/src/views/MoveInfoPage.vue
> Fixed error messages for dates in Move Info Page

- oop/src/views/HomePage.vue
> OOPDEF-127: Added BCSC link to home page.

- oop/src/components/TipBox.vue
- oop/src/views/YourInfoPage.vue
> OOPDEF-51: Added "Tip" box to "Your Info" page.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.15).

- oop/src/components/AddressInput.vue
- oop/src/store/modules/form.js
- oop/src/views/MoveInfoPage.vue
> Added 3 address lines with add and remove buttons

- oop/src/main.js
- oop/src/router/index.js
- oop/src/views/ReviewPage.vue
- oop/src/views/SubmissionErrorPage.vue
> OOP: Added submission error page.

- oop/src/views/MoveInfoPage.vue
> Added tip box for Move Info Page

- oop/src/components/ReviewTableList.vue
> Fixed address lines displayed in Review Page

- oop/src/views/MoveInfoPage.vue
> Add loader in Move Info Page

- oop/src/views/MoveInfoPage.vue
> Remove blank address fields

- oop/src/components/ReviewTable.vue
- oop/src/components/ReviewTableList.vue
> OOP: Review page fixes.

- oop/src/views/MoveInfoPage.vue
> Fixed minor bug on missing address line

- oop/src/components/CountryInput.vue
- oop/src/components/ProvinceInput.vue
- oop/src/components/ReviewTableList.vue
- oop/src/store/states/form-dummy-data.js
- oop/src/views/MoveInfoPage.vue
> OOP: Fixed country/province name on Review page.

- oop/src/views/YourInfoPage.vue
> Phone validation

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.17)

- oop/src/components/DateInput.vue
- oop/src/helpers/validators.js
- oop/src/views/MoveInfoPage.vue
> Fixed BC Validation and css for Move Info Page

- oop/src/views/MoveInfoPage.vue
> OOPDEF-135: Minor text change - Renamed button to 'Review'

- oop/package-lock.json
- oop/src/components/DateInput.vue
- oop/src/components/DatePicker.vue
- oop/src/helpers/user-agent.js
- oop/src/main.js
> OOP: Date picker.

- oop/src/components/ProvinceInput.vue
> Add placeholder for Province

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.18).

- oop/src/views/HomePage.vue
Removed nested `container` divs.
> OOP: Home page alignment.

- oop/src/components/ReviewTable.vue
- oop/src/components/ReviewTableList.vue
- oop/src/views/MoveInfoPage.vue
> OOP: Review page updates.

- oop/package.json
> OOP: Version bump (v0.1.19)

- oop/package-lock.json
- oop/src/components/ReviewTable.vue
- oop/src/components/ReviewTableList.vue
- oop/src/helpers/validators.js
- oop/src/views/MoveInfoPage.vue
> Oop defects

- oop/package.json
> updated version to 0.1.20

- oop/src/views/SubmissionPage.vue
> Fixed tick icon box in mobile version

- oop/src/helpers/validators.js
- oop/src/views/MoveInfoPage.vue
> Added postal code validation for special chars

- oop/package.json
> OOP: Version bump (v0.1.21)

- oop/src/helpers/validators.js
- oop/src/views/MoveInfoPage.vue
- oop/src/views/SubmissionPage.vue
> OOPDEF-152

- oop/package.json
> OOP: Version bump (v0.1.22)

- oop/src/helpers/validators.js
- oop/src/views/MoveInfoPage.vue
> Oopdef 152 bug

- oop/package.json
> OOP: Version bump (v0.1.23)

- oop/src/helpers/validators.js
> Fix BC postal code bug

- oop/package.json
> OOP: Version bump (v0.1.24)

- oop/src/App.vue
- oop/src/components/ProgressBar.vue
- oop/src/main.js
- oop/src/store/index.js
- oop/src/store/modules/app.js
> OOPDEF-104: Stepper mobile.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.25).

- oop/src/components/ProgressBar.vue
- oop/src/components/ReviewTableList.vue
- oop/src/helpers/scroll.js
- oop/src/router/index.js
- oop/src/router/routes.js
- oop/src/views/AccountTypePage.vue
- oop/src/views/HomePage.vue
- oop/src/views/MoveInfoPage.vue
- oop/src/views/ReviewPage.vue
- oop/src/views/SubmissionErrorPage.vue
- oop/src/views/SubmissionPage.vue
- oop/src/views/YourInfoPage.vue
> OOPDEF-143: Navigation guards.

- oop/src/components/ReviewTableList.vue
- oop/src/store/modules/form.js
- oop/src/store/states/form-dummy-data.js
- oop/src/views/HomePage.vue
- oop/src/views/YourInfoPage.vue
- oop/tests/unit/views/YourInfoPage.spec.js
> OOPDEF-156: Remove email field.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.26).

- oop/src/views/SubmissionPage.vue
> OOPDEF-143: Route back to home page when navigating from submission pg.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.27).

- oop/src/components/ReviewTableList.vue
- oop/src/store/modules/form.js
- oop/src/views/MoveInfoPage.vue
> Added new address radio button

- msp-service/src/index.js
> OOP: Added "oopIntegration" to msp-service.

- oop/package-lock.json
- oop/package.json
- oop/src/services/api-service.js
- oop/src/views/AccountTypePage.vue
- oop/src/views/ReviewPage.vue
- oop/src/views/YourInfoPage.vue
> OOPDEF-55: Added API requests and ApiService class.

- oop/package-lock.json
- oop/package.json
- oop/src/helpers/date.js
- oop/src/services/log-service.js
- oop/src/settings.js
- oop/src/views/ReviewPage.vue
- oop/vue.config.js
- openshift/templates/quickoopweb-toall.yaml
> OOP: Implemented log service.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.28).

- oop/src/router/index.js
- oop/src/router/routes.js
- oop/src/services/spa-env-service.js
- oop/src/views/HomePage.vue
- oop/src/views/MaintenancePage.vue
> OOP: Implemented maintenance mode.

- oop/package-lock.json
- oop/src/components/ReviewTableList.vue
- oop/src/views/MoveInfoPage.vue
> OOPDEF-148: Fixed defects raised by Neha on New Address

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.29)

- oop/src/views/MoveInfoPage.vue
> Added text below New Address

- oop/package-lock.json
- oop/package.json
> OOP: Common lib version bump.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.30).

- oop/src/components/Captcha.vue
- oop/src/components/ConsentModal.vue
> OOPDEF-164: Updates to ConsentModal and Captcha component.

- msp-service/src/index.js
> OOP: MSP-Service, bypass nonce URL check.

- oop/src/main.js
- oop/src/services/api-service.js
- oop/src/views/AccountTypePage.vue
- oop/src/views/ReviewPage.vue
- oop/src/views/YourInfoPage.vue
> OOP server validation (work in progress)

- oop/src/components/ReviewTableList.vue
- oop/src/services/api-service.js
- oop/src/views/AccountTypePage.vue
- oop/src/views/YourInfoPage.vue
> Added account type validation based from PHN - work in progress

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.31).

- oop/src/store/states/form-dummy-data.js
- oop/src/views/YourInfoPage.vue
> OOP: Lastname/PHN  server validation.

- oop/src/components/ReviewTableList.vue
- oop/src/views/AccountTypePage.vue
- oop/src/views/YourInfoPage.vue
> OOPDEF-46: Who is Moving

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.32).

- oop/package-lock.json
- oop/package.json
- oop/src/views/YourInfoPage.vue
> OOP: Fix to LastName/PHN validation error message bug.

- oop/src/views/YourInfoPage.vue
> OOPDEF-178: Added returnCode 1 to the switch case for validation

- oop/src/main.js
- oop/src/views/SubmissionPage.vue
> OOPDEF-145: Add info icon on Submission Page

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.33).

- oop/src/helpers/date.js
- oop/src/services/api-service.js
- oop/src/store/modules/form.js
- oop/src/views/ReviewPage.vue
- oop/src/views/SubmissionPage.vue
- oop/src/views/YourInfoPage.vue
> OOPDEF-174: Form submission.

- oop/src/services/api-service.js
- oop/src/store/states/form-dummy-data.js
> OOPDEF-174: Remove formatting from submission payload.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.34).

- oop/src/store/modules/form.js
> OOPDEF-86: Added fields to reset when RESET_FORM action is dispatched.

- oop/src/components/ProvinceInput.vue
- oop/src/components/ReviewTableList.vue
- oop/src/helpers/validators.js
- oop/src/store/states/form-dummy-data.js
> OOPDEF-182: Changed Canadian provinces to store codes instead of names.

- oop/src/services/log-service.js
- oop/src/services/spa-env-service.js
- oop/src/views/HomePage.vue
> Added logging for when "spa-env-server" is down.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.35).

- aop/src/views/SignIn.vue
- aop/src/views/SubmissionInfo.vue
feature addition: Integration of bcsc-service into AOP for authentication
> Bcsc integration

- oop/src/views/AccountTypePage.vue
- oop/src/views/HomePage.vue
- oop/src/views/MoveInfoPage.vue
- oop/src/views/ReviewPage.vue
- oop/src/views/SubmissionErrorPage.vue
- oop/src/views/YourInfoPage.vue
> OOPDEF-86: Navigate to self route updates.

- oop/src/services/api-service.js
- oop/src/views/AccountTypePage.vue
- oop/src/views/YourInfoPage.vue
> OOPDEF-55: Dependents' PHNs validation 

- oop/src/views/AccountTypePage.vue
> Remove spaces to phn and dependent fields

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.36).

- oop/public/index.html
- oop/src/App.vue
- oop/src/components/ProgressBar.vue
- oop/src/components/TipBox.vue
- oop/src/views/YourInfoPage.vue
> OOPDEF-160: Your Info page accessibility.

- oop/src/views/AccountTypePage.vue
> Add accessibility for Account Type Page

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.37)

- oop/src/App.vue
> OOP: Remove padding around `main` element.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.38).

- oop/src/components/CountryInput.vue
- oop/src/components/DateInput.vue
- oop/src/components/ProvinceInput.vue
> Fixed accessibility issues in Move Info Page

- oop/src/views/MoveInfoPage.vue
> OOPDEF-186: Update to error messages.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.39).

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.40).

- oop/package-lock.json
- oop/package.json
- oop/src/views/YourInfoPage.vue
> OOPDEF-124: Added inputStyle props to inputs.

- oop/src/views/AccountTypePage.vue
> OOPDEF-56: Added note below PHN question requested by Neha

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.41).

- spa-env-server/openshift/templates/deploy.yaml
> Updates to `deploy.yaml` for spa-env-server.

- oop/src/router/routes.js
> OOPDEF-196: Updated stepper titles.

- oop/package-lock.json
- oop/src/views/AccountTypePage.vue
- oop/src/views/MoveInfoPage.vue
- oop/src/views/SubmissionPage.vue
- oop/src/views/YourInfoPage.vue
> Updated css and text based from wireframe

- oop/src/components/ReviewTableList.vue
- oop/src/views/MoveInfoPage.vue
> OOPDEF-195: Updated `province` field requirement.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.42).

- oop/src/views/MoveInfoPage.vue
> OOPDEF-195: Province label update.

- splunk-forwarder/src/index.js
> Splunk-forwarder: Fixed infinite loop.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.44).

- oop/src/services/log-service.js
- oop/src/store/states/form-dummy-data.js
- oop/src/views/AccountTypePage.vue
- oop/src/views/HomePage.vue
- oop/src/views/MoveInfoPage.vue
- oop/src/views/ReviewPage.vue
- oop/src/views/SubmissionErrorPage.vue
- oop/src/views/SubmissionPage.vue
- oop/src/views/YourInfoPage.vue
> OOP log updates (submission, errors, and navigation).

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.45).

- address-service/openshift/templates/deploy.yaml
- captcha-service/openshift/templates/deploy.yaml
- msp-service/openshift/templates/deploy.yaml
- oop/openshift/templates/deploy.yaml
- spa-env-server/openshift/templates/deploy.yaml
- splunk-forwarder/openshift/templates/deploy.yaml
> OOPDEF-202: deploy.yaml secrets integration.

- oop/src/views/YourInfoPage.vue
> OOPDEF-203: Added separate error message for `returnCode` === 2.

- oop/src/views/HomePage.vue
> Add console log for splash page

- oop/src/views/HomePage.vue
> Added async and await for maintenance page

- oop/src/views/HomePage.vue
> Remove console log on maintenance flag

- address-service/src/index.js
> Added `AddressLines` prop to address results.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.46).

- oop/package-lock.json
- oop/src/views/MoveInfoPage.vue
> Added customized fields for non-Canada

- oop/src/components/AddressValidator.vue
- oop/src/helpers/address.js
- oop/src/views/MoveInfoPage.vue
> OOPDEF-60: Address validator bug fixes.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.47).

- oop/src/components/ReviewTableList.vue
- oop/src/views/MoveInfoPage.vue
> Fixed bugs in Review Page and Move Info Page

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.48).

- oop/src/views/MoveInfoPage.vue
> OOPDEF-60: Update city max length, when country is Canada.

- oop/src/components/AddressValidator.vue
> OOPDEF-60: Results overflow handling.

- oop/src/components/ReviewTableList.vue
- oop/src/components/StateInput.vue
- oop/src/views/MoveInfoPage.vue
- oop/src/views/ReviewPage.vue
> Fixes issues with US and International Addresses

- oop/src/components/AddressValidator.vue
> OOPDEF-217: Adjusted formatting for AddressValidator note.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.50).

- oop/src/components/AddressValidator.vue
> OOPDEF-217: Updated AddressValidator note.

- oop/src/components/ReviewTableList.vue
- oop/src/components/StateInput.vue
- oop/src/views/MoveInfoPage.vue
> Oopdef 212 bugs

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.51).

- oop/src/components/StateInput.vue
- oop/src/views/MoveInfoPage.vue
> Updated condition for setting address fields to null

- oop/src/components/StateInput.vue
> Updated states alphabetically in the drop down

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.52).

- oop/src/components/AddressValidator.vue
> OOPDEF-217: Update to AddressValidator example address.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.53).

- oop/src/views/YourInfoPage.vue
> OOPDEF-221: Added note on Your Info page.

- oop/src/components/ReviewTable.vue
> OOPDEF-224: Mobile Review page table alignment.

- oop/src/views/MoveInfoPage.vue
> Oopdef 212 bugs v2

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.54).

- oop/src/views/YourInfoPage.vue
> OOPDEF-220: Updated error message on Your Info page.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.55).

- oop/src/components/ReviewTableList.vue
- oop/src/services/api-service.js
- oop/src/views/ReviewPage.vue
> Fixed displayed data on Review and Confirmation Page

- oop/src/components/ReviewTableList.vue
- oop/src/views/MoveInfoPage.vue
> Made all zip codes for OOC optional

- oop/src/views/MoveInfoPage.vue
> OOPDEF-229: Update padding for address line fields in mobile.

- oop/src/services/api-service.js
- oop/src/views/MoveInfoPage.vue
> Replace comma with nothing in JSON payload

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.56).

- oop/src/components/ReviewTableList.vue
- oop/src/components/StateInput.vue
- oop/src/helpers/us-states.js
> OOPDEF-230 - Updated statesList to accommodate changes for US States

- oop/openshift/templates/config.yaml
CCing @bryce-mcmath since you'll likely need to do this for AOP as well. These were items raised by the WAVA scan.
> OOP: Added CORS and caching headers to nginx.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.57).

- oop/src/services/api-service.js
> OOPDEF-232: Added condition for null address line values

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v0.1.58).

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v1.0.0).

- oop/src/views/AccountTypePage.vue
> OOPDEF-233: Updated dependent PHN description text.

- oop/src/views/YourInfoPage.vue
> OOPDEF-234: Updated Your Info page description text.

- oop/src/views/MoveInfoPage.vue
> OOPDEF-235: Updated Move Info page "New Address" description text.

- oop/package-lock.json
- oop/package.json
> OOP: Version bump (v1.0.1).

- aop/src/App.vue
- aop/src/helpers/validators.js
- aop/src/router/index.js
- aop/src/router/routes.js
- aop/src/views/AssignmentOfPaymentHealthAuth.vue
- aop/src/views/ConfirmationHealthAuth.vue
- aop/src/views/LogIn.vue
- aop/src/views/ReviewHealthAuth.vue
- aop/src/views/SendingHealthAuth.vue
- aop/src/views/SessionEndHealthAuth.vue
- aop/src/views/SubmissionErrorHealthAuth.vue
- aop/src/views/SubmissionInfoHealthAuth.vue
Alternate route for health authority users to use to avoid authentication
> Add alternate route for health authority

- aop/package-lock.json
- aop/package.json
- oop/package-lock.json
- oop/package.json
NPM Audit upgrades Axios version, fixes vulnerabilities in all non-dev dependencies
I plan to check the code as best as I can after deploying to dev
> Vulnerability fix-- OOP and AOP

- aop/package-lock.json
- aop/package.json
- oop/package-lock.json
- oop/package.json
Version bump for vulnerability fixes
> Version bump (AOP: 1.1.1, OOP: 1.0.2)

- aop/package-lock.json
- aop/package.json
Chore
https:// must be used instead of git://
> Update common-lib and bootstrap deps

- oop/package-lock.json
- oop/package.json
Chore.
GitHub has deprecated the anonymous usage of the "git://" protocol when specifying them in dependencies. I've updated this to "https://" instead. I've also updated the OOP frontend to use the latest version of the Vue common library, which has been fixed to "https://" as well.
> OOP: dependency updates.

- oop/src/views/MoveInfoPage.vue
Found a few more and fixed them, sorry for the trouble
I think this should be the last of them
> A few more country -> jurisdiction fixes

- oop/package-lock.json
- oop/package.json
Version bump for jurisdiction updates
> Version bump from 1.0.2 to 1.0.3

- oop/.eslintrc.js
- oop/package-lock.json
- oop/package.json
- oop/src/components/ReviewTable.vue
- oop/tests/e2e/specs/happypath1.spec.js
- oop/tests/e2e/specs/happypath2.spec.js
- oop/tests/unit/helpers/scroll.spec.js
- oop/tests/unit/views/ReviewPage.spec.js
Updates Eslint settings (will make a second PR later when I merge into main)
> Vulnerability fixes eslint

- aop/package-lock.json
- aop/package.json
--Update the CLI to resolve the node-ipc vulnerability
--The unit and E2E tests for this project are not currently functional and haven't been for a long time. I want to make a functioning test suite for this project down the road
--That said, I manually tested the happy path for this project and everything seems to superficially work. I don't have the project know-how to check for anything beyond that, unfortunately
> Vulnerability fixes (aop)

- aop/package.json
- oop/package.json
Version bump for node-ipc fixes, AOP and OOP
> Version bump (AOP -> 1.1.3, OOP -> 1.0.4)

- aop/package-lock.json
- aop/src/settings.js
- aop/src/store/dummy-data.js
- aop/src/store/index.js
- aop/src/views/LogIn.vue
Feature addition (easier dev workflow)
You can now bypass BCSC auth during local development by using the `settings.js` and setting both properties to true
> Add login bypass and dummy data for easy dev

- .github/workflows/aop-web.yaml
Chore 
In preparation for the Vue3 upgrade, the node version must be at least 12
> Update github action node version

- aop/src/components/file-uploader/FileUploader.vue
Bug fix/feature addition
Now scaling is only applied when a PDF page is too large, and if a PDF has only blank pages it will show an error message, if it has some blank pages then they will be removed
> Add size checking and handling to AOP fileuploader

- oop/package-lock.json
- oop/package.json
- oop/src/views/MoveInfoPage.vue
> Version bump 1.0.4 -> 2.0.0

- .github/workflows/npm-audit-workflow.yaml
- .github/workflows/oop-web-to-prod.yaml
- .github/workflows/oop-web-to-test.yaml
- .github/workflows/oop-web.yaml
- oop/package-lock.json
- oop/tests/unit/views/MoveInfoPage.spec.js
- oop/tests/unit/views/SubmissionErrorPage.spec.js
- oop/tests/unit/views/SubmissionPage.spec.js
--change workflows to use env variables consistently
--update openshift action to redhat-actions/openshift-tools-installer@v1
--change syntax accordingly
--move default working-directory in oop-web.yaml to only run in the first two jobs, as it caused errors unnecessarily in the third. commented out previous code indicating that a working directory should be used
--added npm run lint back to the oop-web build/deploy code since it's useful
--fix some minor test suite issues caught by the linter
--ran npm audit fix
Unit + e2e tests pass. Lint passes. Prettier run in all changed files. Ran npm audit fix one more time, confirmed that there are 0 production level vulnerabilities.
> Openshift git actions

- oop/package-lock.json
- oop/package.json
- oop/src/views/MoveInfoPage.vue
> Version bump

- .github/workflows/oop-web.yaml
--reintroduce main/push restrictions on the tag action
--use environment variables instead of hardcoded values
The if clause was tested in Github. The build step still works after the variable change. Since there are no changes to the codebase, I believe merging this into main will make this workflow the default one used, so there's no need to re-deploy to TEST in the immediate future.
> Image build if clause

- aop/README.md
> Add more README info

- oop/src/helpers/provinces.js
- oop/src/views/MoveInfoPage.vue
- oop/tests/unit/helpers/provinces.spec.js
--add new function to return abbreviation from spelled out province name
--call abbreviation function when validateFields() is called
--add unit tests for province name functions
Unit and e2e tests pass. Npm run lint passes. Ran Prettier on all code updates. Checked the form state and JSON payload to ensure it stays abbreviated.
> Address abbreviation

- oop/package-lock.json
- oop/package.json
- oop/src/views/MoveInfoPage.vue
> Version bump 2.0.1 -> 2.0.2

- oop/src/components/ReviewTableList.vue
- oop/src/components/StateInput.vue
- oop/src/helpers/us-states.js
- oop/src/services/api-service.js
- oop/src/store/modules/form.js
- oop/src/views/MoveInfoPage.vue
- oop/tests/unit/components/ReviewTableList.spec.js
- oop/tests/unit/helpers/us-states.spec.js
- oop/tests/unit/views/MoveInfoPage.spec.js
--update ReviewTableList to use data instead of addressLine values
--rename StateInput v-model to fix component display bug
--update value to modelValue for Vue 3 upgrade
--create new getStateCodeFromName function to fix api-service axios call
--add tests for that function
--change api-service.js to format jsonPayload correctly, use updated data values
--add new data to store properly
--add new data to setFieldsToNull() function
--update tests to use correct data
Unit and e2e tests all pass (Chrome, Firefox, Edge). Npm run build passes. Ran prettier. Ran npm audit fix; no production vulnerabilities.
> Inf122 issue

- oop/package-lock.json
- oop/package.json
> Version bump for OOP (2.0.2 -> 2.0.3)

- aop/src/store/index.js
- aop/src/views/LogIn.vue
- aop/src/views/Maintenance.vue
- oop/src/store/modules/form.js
- oop/src/views/HomePage.vue
- oop/src/views/MaintenancePage.vue
- [] Tests for these changes were added (if applicable)
OOP: Npm unit tests all pass. Npm e2e tests all pass. Npm lint passes. Npm build passes.
AOP: Npm unit tests all pass. Npm e2e tests do NOT pass; can't bypass the login. Plan to investigate at a later time, but for now, nothing changed should affect anything later in the program. Npm lint passes.  Npm build passes.
> Maintenance message

- oop/src/components/AddressLine.vue
- oop/src/components/PhnInputWrapper.vue
- oop/src/views/MoveInfoPage.vue
- oop/tests/e2e/specs/happypath2.spec.js
--Adds  mounted() function to populate dependent and address line fields with existing Vue store data if there is any
--Adds an e2e test for the dependent fields
--Basic e2e formatting fixes
Npm unit tests pass.  Npm build passes. E2E tests all pass. Npm run lint passes except for two known warnings.
> fix data display bug for address lines and dependent phns

- .github/workflows/aop-web.yaml
Update AOP workflow to use updated action. Tested this workflow in Github and it seems to work fine
> AOP Git workflow

- aop/openshift/templates/build.yaml
Update node version and memory limit in the AOP build.yaml file in case we need to rebuild the build config in OpenShift
> AOP build.yaml update

- .github/workflows/address-service.yaml
- address-service/package-lock.json
The address service workflow didn't work correctly due to package lock issues. This auto-generated update generated by the npm i command should fix this problem.
> Address service workflow fix

- address-service/package-lock.json
- address-service/package.json
- aop/package-lock.json
- aop/package.json
- captcha-service/package-lock.json
- captcha-service/package.json
- msp-service/package-lock.json
- msp-service/package.json
- oop/package-lock.json
- oop/package.json
- spa-env-server/package-lock.json
- spa-env-server/package.json
- splunk-forwarder/package-lock.json
- splunk-forwarder/package.json
Version bump for the applications + the affected services
> Version bump for AOP ( 1.3.0 -> 1.3.1 ) and OOP ( 2.0.3 -> 2.0.4 )

- .github/workflows/oop-web.yaml
- oop/cypress.json
- oop/package-lock.json
- oop/package.json
- oop/tests/e2e/specs/happypath1.spec.js
- oop/tests/e2e/specs/happypath2.spec.js
--add alias for E2E testing to project .json
--add headless E2E test requirement to build workflow
--update test data for new database
--refactor Cypress tests to be less hardcoded
--update default Cypress timeout to account for site slowness
--Unit tests all pass
--Npm run build passes
--Npm run lint has no errors except for expected skipped test warnings
--Ran prettier
--Ran npm audit fix; no production vulnerabilities
--E2e tests pass in Chrome, Firefox, and Edge
> (OOP) Test data updates, Cypress refactoring

- msp-service/package-lock.json
- msp-service/package.json
Revert JWT version so the msp-service pod builds in OpenShift
> Revert JWT version

- .github/pull_request_template.md
- oop/jest.config.js
- oop/package-lock.json
- oop/package.json
--Upgrades axios to the latest version to resolve a vulnerability
--Upgrades the common library version to resolve the same vulnerability
--Changes the Jest config settings to allow for unit testing with the later version of Axios
--Expands the pull request template to cover more points of failure
Everything seems to be working fine, but I did notice some slowdown specifically in the Edge browser. I suspect it's a network + browser problem rather than a problem with the code, but I figured I'd document it in case further action is required later to alleviate it.
> Axios fix (OOP)

- aop/jest.config.js
- aop/package-lock.json
- aop/package.json
--Update Axios version to resolve vulnerability (semver update)
--Update common library version to resolve the same vulnerability
--Change jest config to allow unit testing with the latest version of Axios
--Other minor vulnerability fixes
> Axios fix (AOP)

- aop/package-lock.json
- aop/package.json
- oop/package-lock.json
- oop/package.json
> Version bump for AOP (1.3.1 --> 1.3.2) and OOP (2.0.4 --> 2.0.5)

- oop/src/views/AccountTypePage.vue
- oop/tests/e2e/specs/happypath2.spec.js
Update wording on Account Type Page, update wording in e2e test
> CSA-4: Update wording in AccountTypePage.vue

- msp-service/src/index.js
`npm run start` does NOT pass because it needs environment variables to be passed down. `npm audit` fixes were NOT implemented due to the deadline of completing the Splunk migration.
> Splunk Migration: MSP-Service

- oop/package-lock.json
- oop/src/App.vue
- oop/src/components/AddressLine.vue
- oop/src/components/PhnInputWrapper.vue
- oop/src/services/api-service.js
- oop/src/views/MoveInfoPage.vue
- oop/tests/e2e/specs/happypath1.spec.js
- oop/tests/e2e/specs/happypath2.spec.js
- oop/tests/unit/views/MoveInfoPage.spec.js
- Adds code to update child address line and PHN input wrapper when the parent changes
- Updates API service to push a blank string instead of a null value when data is not present
- Updates city max value to meet requirements for different country/jurisdiction values
- Updates postal code max lengths to meet requirements for different country/jurisdiction values
- Fixes wording error (exceed vs exceeds)
- Adds default option label to province select field
- Fixes text box width issue
- Fixes follows-redirect vulnerability
- Adds unit tests, updates e2e tests
Resolves a number of bug tickets, including CS-100, CS-101, CS-19, CS-23, CS-24, CS-20, CS-21, CS-27, CS-28, CS-25, CS-26, CS-18, CS-17, CS-22, CS-97
> Bug fixes (OOP)

- oop/package-lock.json
- oop/package.json
> Version bump (OOP 2.0.5 -> 2.0.6)

- oop/src/components/ReviewTableList.vue
Fixes review table list issue so it displays consistently whether zip code is blank or an empty string
See ticket CS-114 in Jira
> Fix review table list (OOP)

- oop/cypress.json
- oop/package.json
- oop/tests/e2e/fixtures/dev-data.json
- oop/tests/e2e/fixtures/local-data.json
- oop/tests/e2e/fixtures/test-data.json
- oop/tests/e2e/specs/happypath1.spec.js
- oop/tests/e2e/specs/happypath2.spec.js
--disable video export on headless script run
--add scripts to package.json for dev/test environment e2e testing
--split environment data into separate files so multiple tests can use it
--add code to select environment data based on the baseUrl passed down in the script
--add cypress intercepts so the test suite passes in the Git build action when DEV environment is down
Tested local, dev, and test scripts in all browsers (Chrome, Firefox, Edge, Electron)
> Refactor e2e tests (OOP)
